name: Python API
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  python_package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python3
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Build pip package
        run: python -m pip install --verbose .
      - name: Test installation
        run: mos4d_pipeline --help
